initial commit
redmacdev1988/CarouselPartOne pull request #1
Opened 2022-06-01 02:13 UTC by redmacdev1988

Initial commit.

1) implemented circular array data structure to hold string urls. There are two implementations, one is for OOP, the other for FO. It will act as the carousel.

2) used the circular array in React. React display component Gallery simply checks to see if the structure has been sorted or re-fetched via useEffect.

2022-06-08 03:55 UTC, neotan requested changes

2022-06-08 03:55 UTC, neotan commented on src/CircularList/CircularlArrayFP.ts
> +    _data = [...newDataArr];
generally, `_` is for private variables don't expect manually update in scope, e.g.:

```js
  const product  = {
      _id, // generated by database when inserting
      productName,
      _createdAt, // generated by database when inserting
    }

```

but declaring private variables is not a must, especially when doing so will hurt the readability.

2022-06-09 02:52 UTC, redmacdev1988 commented on src/CircularList/CircularlArrayFP.ts
> +    _data = [...newDataArr];
removed _ for functionality that is returned for public usage.
removed _ for common data structure used.

Question - What do you mean by **private variables don't expect manually update in scope**. 
Like this?
```
let _data = [];
_data = [..._data, newValue]; // manually updated in scope.
```

2022-06-13 07:40 UTC, ginozhu commented on src/CircularList/CircularlArrayFP.ts
> +    strArrData = [newUrl, ...strArrData];
1. We should use deconstruction wisely as the performance is often bad
2. strArrData seems a bit odd, if it has to be a global stateful variable, it doesn't need to be reassigned everytime. If it doesnt, and you wanna keep FP's purity, we shall make it a parameter. (Also good for unit testing)
```
const insertAtFront = (strArrData: string [], newUrl: string)
```

2022-06-16 02:20 UTC, redmacdev1988 commented
https://user-images.githubusercontent.com/13611620/173977010-c70132fa-763b-4e5b-843b-7e4954e44527.mov

2022-07-13 01:01 UTC, merged